CREATE TABLE `application` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `number` varchar(100) NOT NULL,
  `data_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `agency_id` int DEFAULT NULL,
  `route_to` int DEFAULT NULL,
  `route_from` int DEFAULT NULL,
  `transport_to` int DEFAULT NULL,
  `transport_from` int DEFAULT NULL,
  `date_from` date DEFAULT NULL,
  `time_from` time DEFAULT NULL,
  `city_arrival_from` varchar(100) DEFAULT NULL,
  `flight_number_from` varchar(20) DEFAULT NULL,
  `date_to` date DEFAULT NULL,
  `time_to` time DEFAULT NULL,
  `city_arrival_to` varchar(100) DEFAULT NULL,
  `flight_number_to` varchar(20) DEFAULT NULL,
  `comment` varchar(500) DEFAULT NULL,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `application_unique` (`number`),
  UNIQUE KEY `application_unique_1` (`number`,`agency_id`),
  KEY `application_route_FK` (`route_to`),
  KEY `application_route_FK_1` (`route_from`),
  KEY `application_transport_type_FK` (`transport_to`),
  KEY `application_transport_type_FK_1` (`transport_from`),
  KEY `application_agency_FK` (`agency_id`),
  CONSTRAINT `application_agency_FK` FOREIGN KEY (`agency_id`) REFERENCES `agency` (`id`),
  CONSTRAINT `application_route_FK` FOREIGN KEY (`route_to`) REFERENCES `route` (`id`),
  CONSTRAINT `application_route_FK_1` FOREIGN KEY (`route_from`) REFERENCES `route` (`id`),
  CONSTRAINT `application_transport_type_FK` FOREIGN KEY (`transport_to`) REFERENCES `transport_type` (`id`),
  CONSTRAINT `application_transport_type_FK_1` FOREIGN KEY (`transport_from`) REFERENCES `transport_type` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=53 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;